### PR TITLE
Add meson build definitions

### PR DESCRIPTION
**Pull request by igor-raits**
Signed-off-by: Igor Gnatenko i.gnatenko.brain@gmail.com

### CODE REVIEW

**Comment by jpakkane** [comment]
- [x] if new project, master has tagged commit as only commit
- [x] if new branch, it is branched from master
- [x] contains a readme.txt
- [x] contains an upstream.wrap file
- [x] download link points to authoritative upstream location
- [x] wrap repository contains only build system files
- [x] merge request is pointed to correct target branch (not master)
- [x] wrap works
- [x] repo does not have useless top level directory (i.e. libfoobar-1.0.0)

**Comment by jpakkane** [comment]
Does not compile on OSX:

ninja -C build 
ninja: Entering directory `build'
[6/10] Compiling c object enet.dir/callbacks.c.o
FAILED: cc '-DHAS_POLL' '-DHAS_FCNTL' '-DHAS_INET_PTON' '-DHAS_INET_NTOP' '-DHAS_MSGHDR_FLAGS' '-DHAS_SOCKLEN_T' '-Wall' '-Wpedantic' '-Winvalid-pch' '-g' '-Ienet.dir' '-I..' '-I.' '-MMD' '-MQ' enet.dir/callbacks.c.o '-MF' 'enet.dir/callbacks.c.o.d' -o enet.dir/callbacks.c.o -c ../callbacks.c
../callbacks.c:6:10: fatal error: 'enet/enet.h' file not found
#include "enet/enet.h"
         ^
1 error generated.

**Comment by igor-raits** [comment]
@jpakkane hm. can reproduce. working on it

**Comment by igor-raits** [comment]
@jpakkane fixed

**Comment by jpakkane** [comment]
Thanks. Works. Merging.

**Pull request merged**
